### ISSUE TITLE
Cannot use image on gce/gke with persistent disks

### ISSUE THREAD

**Issue by sameersbn** [bitnami/bitnami-docker-mariadb#1]
Using kubernetes, if I use the image on google compute with a persistent disk for the mariadb data the mariadb server exists with filesystem permissions errors.

The following pod description `mariadb.yaml` was used for the test

P.S. replace `bitnami-container-cluster` in the yaml and the commands below with your `PROJECT_ID` from the google developer console

```yaml
apiVersion: v1beta3
kind: Pod
metadata:
  name: mariadb
  labels:
    name: mariadb
spec:
  containers:
    - name: mariadb
      image: gcr.io/bitnami-container-cluster/mariadb
      env:
        - name: MARIADB_PASSWORD
          value: secretpassword
      ports:
        - containerPort: 3306
          name: mariadb
      volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /bitnami/mariadb/data
  volumes:
    - name: mariadb-persistent-storage
      gcePersistentDisk:
        pdName: mariadb-disk
        fsType: ext4
```

Follow the command sequence below to 

```bash
# use google container engine and start the cluster
cd kubernetes
export KUBERNETES_PROVIDER=gke
./cluster/kube-up.sh

# push the mariadb image to the container registry (update `PROJECT_ID` here)
docker tag -f bitnami/mariadb gcr.io/bitnami-container-cluster/mariadb
gcloud preview docker push gcr.io/bitnami-container-cluster/mariadb

# create peristent disk for mariadb data
gcloud compute disks create --zone=us-central1-b --size=200GB mariadb-disk

# start the mariadb pod
kubectl create -f mariadb.yml

# get pod status (wait until we are out of the `PENDING` state)
kubectl get pods/mariadb

# get mariadb logs
kubectl logs -f mariadb
```

The logs show the following error indicating file permission errors

```bash
150617  5:09:01 InnoDB: The InnoDB memory heap is disabled
150617  5:09:01 InnoDB: Mutexes and rw_locks use GCC atomic builtins
150617  5:09:01 InnoDB: Compressed tables use zlib 1.2.3
150617  5:09:01 InnoDB: Using Linux native AIO
150617  5:09:01 InnoDB: Initializing buffer pool, size = 128.0M
150617  5:09:01 InnoDB: Completed initialization of buffer pool
150617  5:09:01  InnoDB: Operating system error number 13 in a file operation.
InnoDB: The error means mysqld does not have the access rights to
InnoDB: the directory.
InnoDB: File name ./ibdata1
InnoDB: File operation call: 'create'.
InnoDB: Cannot continue operation.
```

To cleanup follow the below commands

```bash
# delete the pod
kubectl delete -f mariadb.yml

# delete the persistent disk
gcloud compute disks delete --zone=us-central1-b mariadb-disk

# bring down the cluster
./cluster/kube-down.sh
```
