### ISSUE TITLE
mysql user not exists

### ISSUE THREAD

**Issue by derymukti** [bitnami/bitnami-docker-mariadb#123]
* docker-compose.yml**

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=12345678
      - MARIADB_USER=user
      - MARIADB_PASSWORD=12345678
      - MARIADB_DATABASE=mydb
    volumes:
      - ./db:/var/lib/mysql

```

and im run

**docker-compose up**

```
Starting mariadb_mariadb_1
Attaching to mariadb_mariadb_1
mariadb_1  | 
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | Send us your feedback at containers@bitnami.com
mariadb_1  | 
mariadb_1  | INFO  ==> Starting mariadb... 
mariadb_1  | INFO  ==> Starting mysqld_safe...
mariadb_1  | Could not open required defaults file: /opt/bitnami/mariadb/conf/my.cnf
mariadb_1  | Fatal error in defaults handling. Program aborted
mariadb_1  | WARNING: Defaults file '/opt/bitnami/mariadb/conf/my.cnf' not found!
mariadb_1  | Could not open required defaults file: /opt/bitnami/mariadb/conf/my.cnf
mariadb_1  | Fatal error in defaults handling. Program aborted
mariadb_1  | WARNING: Defaults file '/opt/bitnami/mariadb/conf/my.cnf' not found!
mariadb_1  | 170516 10:56:45 mysqld_safe Logging to '/opt/bitnami/mariadb/data/2a6d8f52738c.err'.
mariadb_1  | 170516 10:56:45 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
mariadb_1  | /opt/bitnami/mariadb/bin/mysqld_safe_helper: Can't change to run as user 'mysql'.  Please check that the user exists!
mariadb_mariadb_1 exited with code 1

```
