### ISSUE TITLE
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal

### ISSUE THREAD

**Issue by qodeboy** [bitnami/bitnami-docker-mariadb#130]
**Description**

After importing a relatively large database, mariadb configured in master-slace cluster fails to start.

**Steps to reproduce the issue:**

1. Create cluster according to README.md in this repository or using docker-compose.yml found below.
2. Import large database to master.
3. Slaves will reject connections.
4. Restart cluster and see "FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal." error.

**Describe the results you received:**

Below is output of ```docker logs mysql-slave-a```

```
Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing mariadb
mariadb INFO  ==> Cleaning data dir...
mariadb INFO  ==> Configuring permissions...
mariadb INFO  ==> Validating inputs...
mariadb INFO  ==> Initializing database...
mariadb INFO  ==> Configuring replication mode slave...
mariadb INFO  ==> Setting up database slave...
mariadb INFO  ==> Checking if replication master is ready to accept connection ...
INFO  Trying to connect to MySQL server
INFO  Found MySQL server listening at master:3306
INFO  MySQL server listening and working at master:3306
mariadb INFO  ==> Setting the master configuration...
mariadb INFO  ==> Creating a data snapshot...
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
/opt/bitnami/base/helpers: line 13:    21 Aborted                 (core dumped) nami ${NAMI_DEBUG:+--log-level ${NAMI_LOG_LEVEL:-trace}} initialize ${module} $inputs "${@:2}"
```

**Describe the results you expected:**

Cluster is started as expected and all nodes able to accept connections. Data is fully synchronised.

**Additional information you deem important (e.g. issue happens only occasionally):**

docker-compose.yml:
```
version: "3"

services:
  master:
    image: bitnami/mariadb:10.1
    container_name: mysql-master
    restart: always
    ports:
      - 3306:3306
    networks:
      - mysql_tier
      - server_tier
    volumes:
      - master_data:/bitnami
      - ./my.cnf:/bitnami/mariadb/conf/my_custom.cnf:ro
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=${MARIADB_REPLICATION_USER}
      - MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  slave-a:
    image: bitnami/mariadb:10.1
    container_name: mysql-slave-a
    restart: always
    ports:
      - 3307:3306
    networks:
      - mysql_tier
      - server_tier
    volumes:
      - ./my.cnf:/bitnami/mariadb/conf/my_custom.cnf:ro
    depends_on:
      - master
    links:
      - master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=${MARIADB_REPLICATION_USER}
      - MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD}
      - MARIADB_MASTER_HOST=master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  slave-b:
    image: bitnami/mariadb:10.1
    container_name: mysql-slave-b
    restart: always
    ports:
      - 3308:3306
    networks:
      - mysql_tier
      - server_tier
    volumes:
      - ./my.cnf:/bitnami/mariadb/conf/my_custom.cnf:ro
    depends_on:
      - master
    links:
      - master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=${MARIADB_REPLICATION_USER}
      - MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD}
      - MARIADB_MASTER_HOST=master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  slave-c:
    image: bitnami/mariadb:10.1
    container_name: mysql-slave-c
    restart: always
    ports:
      - 3309:3306
    networks:
      - mysql_tier
      - server_tier
    volumes:
      - ./my.cnf:/bitnami/mariadb/conf/my_custom.cnf:ro
    depends_on:
      - master
    links:
      - master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=${MARIADB_REPLICATION_USER}
      - MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD}
      - MARIADB_MASTER_HOST=master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      
volumes:
  master_data:
    driver: local

networks:
  mysql_tier:
    driver: bridge
  server_tier:
    external: true
```

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 17
 Running: 15
 Paused: 0
 Stopped: 2
Images: 16
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.91GiB
Name: srv
ID: HMGW:37PF:RLAD:DY45:MSQI:6VZJ:MVMH:Z4D6:H7XF:DQK6:JV7U:Q5QE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.16.1, build 6d1ac219
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```
