### ISSUE TITLE
Failed to use custom configuration.

### ISSUE THREAD

**Issue by seli** [bitnami/bitnami-docker-mariadb#135]
**Description**

When launching the bitnami-docker-mariadb, I get the following error:
Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/mariadb/conf/my.cnf'

**Steps to reproduce the issue:**
First possibility:
1. In the docker-compose.yml file configure a volume like e.g. ../conf/mariadb:/bitnami/mariadb/conf containing the file my_custom.cnf
2. Launch the docker via docker-compose
3. Watch logging

Second possibility:
1. Use the following Dockerfile to build an image:
```
FROM bitnami/mariadb:latest
MAINTAINER your name <your.name@mail.com>

COPY my_custom.cnf /bitnami/mariadb/conf/my_custom.cnf
```
2. Launch the docker via docker-compose
3. Watch logging

**Describe the results you received:**
Both possibilities result in the same error in the log:

Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/mariadb/conf/my.cnf'

Without configuring or copying the my_custom.cnf file, the error isn't seen.

**Describe the results you expected:**

A mariadb to be launched with the merged config

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`: 

```
Docker version 17.09.0-ce, build afdb6d4
```

- Output of `docker info`:

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 1m3p263tq8bxvcmpji9sjo2n7
 Is Manager: true
 ClusterID: y519e8rdspjiarp87spwcn568
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.211.55.40
 Manager Addresses:
  10.211.55.40:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-37-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.79GiB
Name: eppix-rietveld-deb
ID: ILOF:VX5W:YC4Y:KQI4:77X6:XO67:LLKO:VU4R:PWFT:OPF3:2SE2:BAIO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.16.1, build 6d1ac21
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by pprazzi** [comment]
I have the same problem

In my docker-compose I have stated 

```yaml
 mariadb-master:
    image: <removed>
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/bitnami
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=<removed>
      - MARIADB_REPLICATION_PASSWORD=<removed>
      - MARIADB_ROOT_PASSWORD=<removed>
      - MARIADB_DATABASE=<removed>
      - MARIADB_USER=<removed>
      - MARIADB_PASSWORD=<removed>
    networks:
      main:
        aliases:
          - MARIA-DB
...

volumes:
  db-data:
  db-data-slave:
networks:
  main:
    driver: bridge

```

my DockerFile looks like this 

```
FROM bitnami/mariadb:latest
MAINTAINER Jan Castermans <jan.castermans@inapps.be>

USER 1001

COPY utf8mb4.cnf /bitnami/mariadb/conf/utf8mb4.cnf

```
The line `USER 1001` was added, but didn't make any difference

==>
Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/mariadb/conf/my.cnf'
