### ISSUE TITLE
`EACCES: permission denied` error when trying to add a persistence volume

### ISSUE THREAD

**Issue by nmrshll** [bitnami/bitnami-docker-mariadb#136]
On Ubuntu 16.04.1, linux 4.8.0-46-generic x86_64,

When trying to add persistence to the mariadb container through docker volumes, I'm presented with this error:

`Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb'`

The docker-compose file I'm using looks like that:

```
version: '2'
services:
  myapp:
    image: 'bitnami/codeigniter:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_USER=someuser
      - MARIADB_ROOT_PASSWORD=shhhhhhhh
      - MARIADB_DATABASE=somedbdev
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql:/bitnami
```

Logs:

```
me@Nicolas-Lenovo-Flex2-15:~/src/gitlab.com/voyagelangue/crm-codeigniter/bitnami-codeigniter$ docker-compose up
Recreating bitnamicodeigniter_mariadb_1 ...
Recreating bitnamicodeigniter_mariadb_1 ... done
Recreating bitnamicodeigniter_myapp_1 ...
Recreating bitnamicodeigniter_myapp_1 ... done
Attaching to bitnamicodeigniter_mariadb_1, bitnamicodeigniter_myapp_1
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | Send us your feedback at containers@bitnami.com
mariadb_1  |
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
myapp_1    | Starting application ...
myapp_1    |
myapp_1    | Welcome to the Bitnami codeigniter container
myapp_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-codeigniter
myapp_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-codeigniter/issues
myapp_1    | Send us your feedback at containers@bitnami.com
myapp_1    |
myapp_1    | App already created
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | mariadb INFO  ==> Validating inputs...
mariadb_1  | mariadb INFO  ==> Initializing database...
mariadb_1  | mariadb INFO  ==> Creating 'voyagelanguedev' user with unrestricted access...
mariadb_1  | mariadb INFO  ==> Creating database voyagelanguedev...
mariadb_1  | mariadb INFO  ==> Enabling remote connections...
mariadb_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb'
bitnamicodeigniter_mariadb_1 exited with code 1
```

**Comment by Silvenga** [comment]
Yeah, same problem, this was broken here https://github.com/bitnami/bitnami-docker-mariadb/commit/db5541ff62ce8018efeb6f5bf2c6ad98181c619a#diff-2e7d0295733a50bc79a2bc6dce78ce0fR33

`chown 1001:1001 -R ./datadirectory` fixes the error.

**Comment by laupow** [comment]
This issue is present on GCE & Kubernetes, too. 

Creating a fresh persistent disk, mounting it at `/bitnami`, and running the container results in a restart loop:

```
$ kubectl describe po mariadb-6656995b57-tlgf4
Name:           mariadb-6656995b57-tlgf4
Namespace:      default
Node:           gke-cluster-1-high-cpu-a66fc6d9-q4wk/10.128.0.6
Start Time:     Sun, 12 Nov 2017 10:49:20 -0600
Labels:         pod-template-hash=2212551613
                service=mariadb
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"mariadb-6656995b57","uid":"6e09c2b2-c7c9-11e7-be3c-42010a80010e"...
                kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container carleton-preprod-mariadb
Status:         Running
IP:             10.8.4.18
Created By:     ReplicaSet/mariadb-6656995b57
Controlled By:  ReplicaSet/mariadb-6656995b57
Containers:
  carleton-preprod-mariadb:
    Container ID:   docker://826218fa11751b1e8560bb2161b79b3ca49e6b99f10d035e7c947327960d5025
    Image:          gcr.io/kube-test-185012/mariadb
    Image ID:       docker-pullable://gcr.io/kube-test-185012/mariadb@sha256:b5537f013f56a0403ae4b31d5be89a71a32bd4410f9e85aeaba8f3884ba5212d
    Port:           <none>
    State:          Running
      Started:      Sun, 12 Nov 2017 10:50:48 -0600
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:  100m
    Environment:
      MARIADB_DATABASE:       <set to the key 'MARIADB_DATABASE' of config map 'mariadb-env'>       Optional: false
      MARIADB_PASSWORD:       <set to the key 'MARIADB_PASSWORD' of config map 'mariadb-env'>       Optional: false
      MARIADB_ROOT_PASSWORD:  <set to the key 'MARIADB_ROOT_PASSWORD' of config map 'mariadb-env'>  Optional: false
      MARIADB_USER:           <set to the key 'MARIADB_USER' of config map 'mariadb-env'>           Optional: false
    Mounts:
      /bitnami from wp-preprod-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-b4g3s (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  wp-preprod-db:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     db-data
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  default-token-b4g3s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-b4g3s
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From                                           Message
  ----    ------                 ----  ----                                           -------
  Normal  Scheduled              1m    default-scheduler                              Successfully assigned mariadb-6656995b57-tlgf4 to gke-cluster-1-high-cpu-a66fc6d9-q4wk
  Normal  SuccessfulMountVolume  1m    kubelet, gke-cluster-1-high-cpu-a66fc6d9-q4wk  MountVolume.SetUp succeeded for volume "default-token-b4g3s"
  Normal  SuccessfulMountVolume  36s   kubelet, gke-cluster-1-high-cpu-a66fc6d9-q4wk  MountVolume.SetUp succeeded for volume "wp-preprod-db"
  Normal  Pulling                36s   kubelet, gke-cluster-1-high-cpu-a66fc6d9-q4wk  pulling image "gcr.io/kube-test-185012/mariadb"
  Normal  Pulled                 16s   kubelet, gke-cluster-1-high-cpu-a66fc6d9-q4wk  Successfully pulled image "gcr.io/kube-test-185012/mariadb"
  Normal  Created                16s   kubelet, gke-cluster-1-high-cpu-a66fc6d9-q4wk  Created container
  Normal  Started                15s   kubelet, gke-cluster-1-high-cpu-a66fc6d9-q4wk  Started container
mlauer60769:~ mlauer$ kubectl logs -f mariadb-6656995b57-tlgf4

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing mariadb
mariadb INFO  ==> Cleaning data dir...
mariadb INFO  ==> Configuring permissions...
mariadb INFO  ==> Validating inputs...
mariadb INFO  ==> Initializing database...
mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb INFO  ==> Creating database wordpress...
mariadb INFO  ==> Creating user wordpress...
mariadb INFO  ==> Granting access to wordpress to the database wordpress...
mariadb INFO  ==> Enabling remote connections...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb'
mlauer60769:~ mlauer$ 
```

**Comment by prydonius** [comment]
@laupow are you using the kubernetes.yml file in this repo? It should run an init container that fixes the permissions. You might need to try setting the fsGroup of the volumes (https://github.com/kubernetes/charts/blob/master/stable/mariadb/templates/deployment.yaml#L16).

@Silvenga @n-marshall you need to ensure that the host path you're mounting has group id 0 and rwx permissions for the group. In other words `chown :root ./datadirectory && chmod g+rwX ./datadirectory`.

**Comment by laupow** [comment]
@prydonius Thanks, yes, that's the right direction. I was migrating some other kubernetes configs to this image. The helm templates are a good reference, and I'm glad they exist. Thanks!

**Comment by prydonius** [comment]
@laupow good to know, thanks! cc @sameersbn we should update the kubernetes.yml file in this repo.

**Comment by ljavierrivera** [comment]
I'm getting this error on mac using Docker Toolbox also. Changing the chown and chmod on the datadirectory does NOT resolve the issue.

Any thoughts?

**Comment by chipironcin** [comment]
@ljavierrivera 
To which user are you chown'ing and with which permissions are you chmod'ing?

**Comment by ljavierrivera** [comment]
I followed the above suggestions:
* `chown 1001:1001 -R ./datadirectory`
* `chown :root ./datadirectory && chmod g+rwX ./datadirectory`

where datadirectory is my host directory.

**Comment by chipironcin** [comment]
Have you run those commands as root user? Maybe permissions werent applied successfully.
If it is still not working maybe @sameersbn and @prydonius can help you out.

Expect a small delay on issue responses as per the holiday season 😁

**Comment by jose-carmona** [comment]
Hi!

I had the same problem running on TravisCI: log --> https://travis-ci.org/auroraprj/web/builds/322348742.

```
mariadb_1 | mariadb INFO ==> Enabling remote connections...
mariadb_1 | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb'

```

 I filed a issue in my project --> auroraprj/web#41

Take a look in [Stackoverflow](https://stackoverflow.com/a/45244373)

See this [commit](https://github.com/auroraprj/web/commit/737cf895bb4033eb6affab2a7ea35fd3d2fce2f0) solve the issue for me.

I hope it help.

**Comment by sameersbn** [comment]
with docker-compose a possible workaound is to create a separate container that will perform the chown and exit... f.e.

```yaml
version: '2'
services:
  myapp:
    image: 'bitnami/codeigniter:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
  fix-mariadb-permissions:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - /tmp/data/mysql:/bitnami
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_USER=someuser
      - MARIADB_ROOT_PASSWORD=shhhhhhhh
      - MARIADB_DATABASE=somedbdev
    ports:
      - '3306'
    volumes:
      - /tmp/data/mysql:/bitnami
    depends_on:
      - fix-mariadb-permissions
```

**Comment by f0restgump92** [comment]
Small correction to @sameersbn 

Create data container for mounted folders and give appropriate permission when sidekick container starts
For docker compose:

```
docker-compose.yml 
version: '2'
services:
  replication-master:
    image: bitnami/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: rep_user
      MARIADB_REPLICATION_PASSWORD: rep_pass
      MARIADB_USER: mysql_user
      MARIADB_PASSWORD: mysql_password
      MARIADB_DATABASE: mysql_db
    volumes_from:
    - mysql-data
    ports:
    - 3306:3306/tcp
  replication-slave:
    image: bitnami/mariadb:latest
    environment:
      MARIADB_REPLICATION_MODE: slave
      MARIADB_REPLICATION_USER: rep_user
      MARIADB_REPLICATION_PASSWORD: rep_pass
      MARIADB_MASTER_HOST: replication-master
      MARIADB_MASTER_ROOT_PASSWORD: pass
    ports:
    - 3307:3306/tcp
  mysql-data:
    image: busybox
    volumes:
    - /var/lib/mysql:/bitnami
    command:
    - chown -R  - 1001:1001 - /bitnami

```

**Comment by v-six** [comment]
Those persistence volume problems could be solved by adding two more ENV vars like PUID and PGID in order to customize folder rights. 

Here is the `linuxserver` script that is creating an abc:abc user in the container using given PUID and PGID : https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/cont-init.d/10-adduser. 
Then what you'll just need to add `chown -R abc:abc /bitnami` in Dockerfile and use the flag `--user=abc` when launching the `mysqld_safe` daemon.

**Comment by tompizmor** [comment]
@v-six I am not sure if that will help here

The problem is that the mariadb container run as non-root user so it does not have privileges to run any `chown` or `chmod` commands once the container has started.

**Comment by welkie** [comment]
Just wanted to comment that I needed to use this image for the `bitnami/matomo` image, and I encountered this problem too. The advice above, to run the commands `chown :root ./datadirectory && chmod g+rwX ./datadirectory` worked for me. I was able to start my docker-compose stack without encountering the issue with the bitnami/mariadb container.

**Comment by nozino** [comment]
how about this...
run the command as a root and change owner of the data directory to '1001:1001'
it works for me.

`    spec:
      #securityContext:
      #  runAsUser: 1001
      #  fsGroup: 1001
      initContainers:
      - name: "copy-custom-config"
        image: "busybox"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        command: ["sh", "-c", "mkdir -p /bitnami/mariadb/conf && cp /bitnami/mariadb_config/my.cnf /bitnami/mariadb/conf/my_custom.cnf && chown 1001:1001 -R /bitnami/mariadb"]
        volumeMounts:
        - name: config
          mountPath: /bitnami/mariadb_config
        - name: data
          mountPath: /bitnami/mariadb
`

**Comment by tompizmor** [comment]
@nozin yes, that is basically the workaround proposed [here](https://github.com/bitnami/bitnami-docker-mariadb/issues/136#issuecomment-354644226) but using a docker-compose approach. Check how the `fix-mariadb-permissions` service is doing basically the same that the initContainer in the helm chart

**Comment by theGC** [comment]
I've been struggling with this same error and none of the above changes has any effect. I've pushed the details to SO:

[https://stackoverflow.com/questions/49278090/configure-kubernetes-bitnami-mariadb-container-to-mount-minikube-volume](https://stackoverflow.com/questions/49278090/configure-kubernetes-bitnami-mariadb-container-to-mount-minikube-volume)

In summary I've tried:

- Setting up an **initContainer** running busybox to change the permissions, i.e. `command: ["sh", "-c", " chown 1001:1001 -R /bitnami/mariadb"]`. This fails to complete the **initContainer** set up, and checking the logs its hitting an i/o error when trying to  `chown` all the files.
- Removing the **initContainer** and changing the directory user:group on my local machine before mounting it to **minikube**, i.e. `sudo chown -R 1001:1001 <src-dir>`. This mounts on the minikube vm with a user:group of docker but has permission denied error when trying to attach to mariadb container.
- runAsUser: 1001, fsGroup: 1001 - same permissions error

At this stage I'm a little lost as others seem to of fixed this issue with one of the above solutions. If anyone has any further ideas it would be much appreciated.

**Comment by nozino** [comment]
@theGC If you just want to do some thing with existed helm chart, do like below before executing "helm install" command :

change permission of '/data/staging/sumatra/mariadb-data' to 777
`chmod 777 -R /data/staging/sumatra/mariadb-data`
or
`chown 1001:1001 -R /data/staging/sumatra/mariadb-data`

**Comment by theGC** [comment]
@nozino thank you for having a look at this. Unfortunately, those settings are already present:

![screen shot 2018-03-15 at 13 39 41](https://user-images.githubusercontent.com/1188840/37513340-b8b7404a-28fc-11e8-9939-285d8ffe83b4.png)

that's the directory on the minikube vm.

I'm not currently using Helm for this container but perhaps that'll fix what I'm missing. I'm able to get these volumes mounting in production on Google Cloud Kubernetes. I can also get it all working in docker-compose so I may just revert to compose for dev and leave Kubernetes for production.

**Comment by prydonius** [comment]
@theGC the host volume provisioner in Minikube is known to have issues (https://github.com/kubernetes/minikube/issues/1990), have you tried configuring it to run as root by setting `runAsUser: 0`?

**Comment by Tyil** [comment]
Why was the `USER` directive included if it breaks this image for everyone using a relative volume for persistent storage? It seems the `USER` directive was included back in October, and this issue still exists.

**Comment by tompizmor** [comment]
@Tyil We adopted the non-root approach as it improves the security of the container and it makes the container compatible with the default security policies of OpenShift.

You can still launch the container as root user via command line:

```
$ docker run -it --user root -e ALLOW_EMPTY_PASSWORD=yes bitnami/mariadb:latest
```

or via docker-compose file:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    user: root
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
```
