### ISSUE TITLE
Host '172.18.0.3' is not allowed to connect to this MariaDB server

### ISSUE THREAD

**Issue by ssatz** [bitnami/bitnami-docker-mariadb#154]
**Description**

Host '172.18.0.3' is not allowed to connect to this MariaDB server

**Steps to reproduce the issue:**

```yaml
mariadb-master:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    volumes:
      - 'mariadb_master_data:/bitnami'
    environment:
    - MARIADB_ROOT_PASSWORD=root_password
    - MARIADB_REPLICATION_MODE=master
    - MARIADB_REPLICATION_USER=my_repl_user
    - MARIADB_REPLICATION_PASSWORD=my_repl_password
    - MARIADB_USER=my_user
    - MARIADB_PASSWORD=my_password
    - MARIADB_DATABASE=my_database

  mariadb-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
    - MARIADB_ROOT_PASSWORD=root_password
    - MARIADB_REPLICATION_MODE=slave
    - MARIADB_REPLICATION_USER=my_repl_user
    - MARIADB_REPLICATION_PASSWORD=my_repl_password
    - MARIADB_MASTER_HOST=master
    - MARIADB_MASTER_ROOT_USER=my_user
    - MARIADB_MASTER_ROOT_PASSWORD=my_password
    - MARIADB_USER=my_user
    - MARIADB_PASSWORD=my_password
    - MARIADB_DATABASE=my_database

volumes:
  mariadb_master_data:
    driver: local

```

**Describe the results you received:**

> Attaching to dailyonlinejobs_mariadb-slave_1
> mariadb-slave_1   | 
> mariadb-slave_1   | Welcome to the Bitnami mariadb container
> mariadb-slave_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
> mariadb-slave_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
> mariadb-slave_1   | 
> mariadb-slave_1   | nami    INFO  Initializing mariadb
> mariadb-slave_1   | mariadb INFO  ==> Cleaning data dir...
> mariadb-slave_1   | mariadb INFO  ==> Configuring permissions...
> mariadb-slave_1   | mariadb INFO  ==> Validating inputs...
> mariadb-slave_1   | mariadb INFO  ==> Initializing database...
> mariadb-slave_1   | mariadb INFO  ==> Configuring replication mode slave...
> mariadb-slave_1   | mariadb INFO  ==> Setting up database slave...
> mariadb-slave_1   | mariadb INFO  ==> Checking if replication master is ready to accept connection ...
> mariadb-slave_1   | INFO  Trying to connect to MySQL server
> mariadb-slave_1   | Error executing 'postInstallation': Failed to connect to master:3306 after 36 tries

**Describe the results you expected:**

Expecting slave to connect the master

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):   MAC OS**

**Comment by ssatz** [comment]
@carrodher 👍  sorry my bad.  Issue resolved!
Thanks 💯

**Comment by ssatz** [comment]
@carrodher  I have updated the docker image. Strangely again i am getting same issue. 

slave log
```
mariadb-slave     | 
mariadb-slave     | Welcome to the Bitnami mariadb container
mariadb-slave     | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb-slave     | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb-slave     | Send us your feedback at containers@bitnami.com
mariadb-slave     | 
mariadb-slave     | INFO  ==> ** Starting MariaDB setup **
mariadb-slave     | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
mariadb-slave     | INFO  ==> Initializing mariadb database...
mariadb-slave     | INFO  ==> Installing database...
mariadb-slave     | INFO  ==> Starting mariadb in background...
mariadb-slave     | INFO  ==> Configuration replication mode...
mariadb-slave     | INFO  ==> Checking if replication master is ready to accept connection ...
```
I am not able to log into slave container with root password, i am getting access denied error!
`docker exec -it mariadb-slave bash`

**Comment by ssatz** [comment]
i have added container_name in the service.  I need json data type so i have updated the debian 10.2.17 image . Below is my docker-compose.yml file

```
  mariadb-master:
    image: 'bitnami/mariadb:10.2.17-debian-9-r36'
    container_name: mariadb-master
    volumes:
      - db-master-data:/bitnami/mariadb
    ports:
      - 32797:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=my_repl_user
      - MARIADB_REPLICATION_PASSWORD=my_repl_password
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=dailyonlinejobs
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes

  mariadb-slave:
    image: 'bitnami/mariadb:10.2.17-debian-9-r36'
    container_name: mariadb-slave
    ports:
     - 32796:3306
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=my_repl_user
      - MARIADB_REPLICATION_PASSWORD=my_repl_password
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_USER=my_user
      - MARIADB_MASTER_PASSWORD=my_password
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=dailyonlinejobs
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes

  volumes:
  db-master-data:
    driver: local
```
when i run 
`docker logs mariadb-slave`

and i get the below log
```
mariadb-slave     | 
mariadb-slave     | Welcome to the Bitnami mariadb container
mariadb-slave     | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb-slave     | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb-slave     | Send us your feedback at containers@bitnami.com
mariadb-slave     | 
mariadb-slave     | INFO  ==> ** Starting MariaDB setup **
mariadb-slave     | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
mariadb-slave     | INFO  ==> Initializing mariadb database...
mariadb-slave     | INFO  ==> Installing database...
mariadb-slave     | INFO  ==> Starting mariadb in background...
mariadb-slave     | INFO  ==> Configuration replication mode...
mariadb-slave     | INFO  ==> Checking if replication master is ready to accept connection ...
```

**Comment by carrodher** [comment]
It seems you hace some typos in the environment variables that produce some connection errors like
```
2018-10-02  9:09:01 139660475389696 [Warning] Access denied for user 'root'@'172.28.0.3' (using password: NO)
```
I found those errors accessing to the master container and taking a look to the logs using
```bash
tail -f /opt/bitnami/mariadb/logs/mysqld.log
```


Can you try using this `docker-compose.yml`? Is the same that you shared above but fixing the typos:
```yaml
mariadb-master:
  image: 'bitnami/mariadb:10.2.17-debian-9-r36'
  container_name: mariadb-master
  volumes:
    - 'db-master-data:/bitnami/mariadb'
  ports:
    - 32797:3306
  environment:
    - MARIADB_REPLICATION_MODE=master
    - MARIADB_REPLICATION_USER=my_repl_user
    - MARIADB_REPLICATION_PASSWORD=my_repl_password
    - MARIADB_ROOT_PASSWORD=root_password
    - MARIADB_USER=my_user
    - MARIADB_PASSWORD=my_password
    - MARIADB_DATABASE=dailyonlinejobs

mariadb-slave:
  image: 'bitnami/mariadb:10.2.17-debian-9-r36'
  container_name: mariadb-slave
  ports:
    - 32796:3306
  depends_on:
    - mariadb-master
  environment:
    - MARIADB_REPLICATION_MODE=slave
    - MARIADB_REPLICATION_USER=my_repl_user
    - MARIADB_REPLICATION_PASSWORD=my_repl_password
    - MARIADB_MASTER_HOST=mariadb-master
    - MARIADB_MASTER_ROOT_PASSWORD=root_password
```

You can add other env variables, but check the ones related to password, [here](https://github.com/bitnami/bitnami-docker-mariadb#setting-up-a-replication-cluster) you can find an example about how to configure it in a replication way.
