### ISSUE TITLE
stable/mariadb helm chart db container fails to start

### ISSUE THREAD

**Issue by lbudai74** [bitnami/bitnami-docker-mariadb#157]
**Description**

**Steps to reproduce the issue:**

1. helm install --name mariadb stable/mariadb

**Describe the results you received:**
The mariadb container keeps restarting, and the container log shows the following message:

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues

nami    INFO  Initializing mariadb
mariadb INFO  ==> Cleaning data dir...
mariadb INFO  ==> Configuring permissions...
mariadb INFO  ==> Validating inputs...
mariadb INFO  ==> Initializing database...
mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb INFO  ==> Creating database my_database...
mariadb INFO  ==> Configuring replication mode master...
mariadb INFO  ==> Creating replication user replicator...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb/data'

**Describe the results you expected:**

To have the mariadb running properly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

- Output of `docker info`:

```
Containers: 14
 Running: 12
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 18.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker-252:1-16938451-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.444GB
 Data Space Total: 107.4GB
 Data Space Available: 4.35GB
 Metadata Space Used: 3.219MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.144GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.6.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.461GiB
Name: worker2
ID: CTNJ:2UHE:N6E6:I36Y:VVL4:T6T3:X5IO:7MAB:PJ7C:QTGN:CYSH:AORX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.

```

- Output of `docker-compose version` (if applicable):

```
N/A
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

It is a test kubernetes cluster running on KVM VMs. it has 1 master node and 3 "worker" nodes. Persistent Volumes are provided by gluster.
The version of the chart: mariadb-4.4.2.

**Comment by juan131** [comment]
Hi @lbudai74 

Did the PVs attached to your MariaDB pods already exist or were they dynamically created by your provider? 

The PV permissions should have been adapted according the the SecurityContext you can find below:
https://github.com/helm/charts/blob/master/stable/mariadb/templates/master-statefulset.yaml#L24

Could you mount the volume on a **busybox** container and inspect the permissions on it? Please share with us what you find.

**Comment by lbudai74** [comment]
Hello @juan131 

Thank you for your answer.

My PV already exists when I'm trying to install the chart. The PVs are created wit the following yaml:
```
kind: PersistentVolume
apiVersion: v1
metadata:
    name: pv0001
    labels:
         type: gluster
spec:
    capacity:
        storage: 15Gi
    accessModes:
        - ReadWriteOnce
    glusterfs:
        endpoints: "glusterfs-cluster"
        path: "/vol1"
        readOnly: false
```

Regarding the busybox test I hope I understood correctly what you're asking from me ... I've done the following:
1. Create a Pod using this yaml file:
```
apiVersion: v1
kind: Pod
metadata:
  name: glusterfs
spec:
  containers:
  - name: glusterfs
    image: busybox
    command:
      - sleep
    args: 
      - "3600"

    volumeMounts:
    - mountPath: "/mnt/glusterfs1"
      name: glusterfsvol1
  volumes:
  - name: glusterfsvol1
    persistentVolumeClaim:
      claimName: data-mariadb-mariadb-0
```

2. exec into the pod and do ls -al on the mount point:
```
$ kubectl exec -ti glusterfs sh
# df /mnt/glusterfs1
Filesystem           1K-blocks      Used Available Use% Mounted on
10.10.10.1:/vol2     126975232   9140096 113692544   7% /mnt/glusterfs1
# ls -al /mnt/glusterfs1
total 4
drwxr-xr-x    3 root     root          4096 Sep 16 12:09 .
drwxr-xr-x    3 root     root            24 Sep 17 22:18 ..
```
So I see the owner being root, and the group being root as well. I suppose that's the reason for the failure. What can I do to fix it? 

Kind regards,
Laszlo
