### ISSUE TITLE
Can't name default user database to `default` on replication cluster

### ISSUE THREAD

**Issue by astleychen** [bitnami/bitnami-docker-mariadb#164]
**Description**
When using replication cluster of Mariadb, I found that the replication user will not be created on the master node, with which the slave node can't connect to master successfully.

Set `MARIADB_DATABASE=default` to master environment variable.

**Steps to reproduce the issue:**

1. Run with docker-compose to reproduce

```yaml
version: '2'

services:
  mariadb-master:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    volumes:
      - 'mariadb_master_data:/bitnami'
    environment:
      - MARIADB_ROOT_PASSWORD=master_root_password
      - MARIADB_PASSWORD=my_password
      - MARIADB_REPLICATION_PASSWORD=my_repl_password
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=replicator
      - MARIADB_USER=wordpress
      - MARIADB_DATABASE=default
      #- ALLOW_EMPTY_PASSWORD=true #is recommended only for development.
  mariadb-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_PASSWORD=my_repl_password
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=replicator
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      #- ALLOW_EMPTY_PASSWORD=true #is recommended only for development.

volumes:
  mariadb_master_data:
    driver: local
```

2. Connect to master through mysql client.
3. Query users
```bash
MariaDB [(none)]> select user,host from mysql.user;
```

**Describe the results you received:**
User `replicator` was not created.

**Describe the results you expected:**
User `replicator` should be created.

**Additional information you deem important (e.g. issue happens only occasionally):**
