### ISSUE TITLE
TokuDB is broken

### ISSUE THREAD

**Issue by WhiteWind** [bitnami/bitnami-docker-mariadb#168]
**Description**

TokuDB is broken, probably by this commit: https://github.com/bitnami/bitnami-docker-mariadb/commit/e8ce1e3a90ebe7a6e06a9e4f6adbe9295c14ae30

**Steps to reproduce the issue:**

1. docker-compose.yml:
```
    db:
        image: 'bitnami/mariadb:10.1.36-debian-9-r32'
        expose:
          - "3306"
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - database:/bitnami/mariadb
          - ./mysql/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
```
2. my_custom.cnf:
```
    [mysqld]
    plugin-load=ha_tokudb
```
3. docker-compose up db

**Describe the results you received:**
tag 10.1.36-debian-9-r32:
```
    db_1            | INFO  ==> ** Starting MariaDB **
    db_1            | 2018-10-16  6:18:14 140630553246656 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.36-MariaDB) starting as process 1 ...
    db_1            | 2018-10-16  6:18:14 140630553246656 [ERROR] Can't open shared library '/opt/bitnami/mariadb/opt/bitnami/mariadb/plugin/ha_tokudb.so' (errno: 29, cannot open shared object file: No such file or directory)
    db_1            | 2018-10-16  6:18:14 140630553246656 [ERROR] Couldn't load plugins from 'ha_tokudb.so'.
```
**Describe the results you expected:**
Tag 10.1.36-debian-9-r31:
```
db_1            | INFO  ==> ** Starting MariaDB **
db_1            | 181016 06:15:50 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
db_1            | 181016 06:15:50 mysqld_safe Starting mysqld daemon with databases from /bitnami/mariadb/data
```
**Additional information you deem important (e.g. issue happens only occasionally):*

Works in r31, stopped working in r32
