### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'localhost' . 

### ISSUE THREAD

**Issue by dbjpanda** [bitnami/bitnami-docker-mariadb#176]
**Description**

**Steps to reproduce the issue:**
When trying to replicate only one database with `--binlog-do-db=drupal` and `--replicate-do-db=drupal` it says Access denied for user 'root'@'localhost' .  Note if I import the sql dump I am able to work the same but without importing the dump I get this error. 
```

mariadb-master:
    container_name: test-master
    image:  bitnami/mariadb
    restart: always
    volumes:
      - database:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_USER=test
      - MARIADB_PASSWORD=pass
      - MARIADB_DATABASE=drupal
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_EXTRA_FLAGS=--binlog-do-db=drupal
    networks:
      - drupal


  mariadb-slave:
    container_name: test-slave
    image:  bitnami/mariadb
    restart: always
    volumes:
      - database:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_USER=test
      - MARIADB_PASSWORD=pass
      - MARIADB_DATABASE=drupal
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=test-master.mariadb
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=pass
      - MARIADB_EXTRA_FLAGS=--replicate-do-db=drupal
    networks:
      - drupal

```
**Describe the results you received:**

```
Slave I/O thread: connected to master 'repl_user@witbix-master.mariadb:3306',replication started in log 'FIRST' at position 4
2018-12-31  1:29:38 140385802913600 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.2.20-MariaDB-log'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
2018-12-31  1:29:51 140385711261440 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
2018-12-31  1:30:31 140385711261440 [Warning] Access denied for user 'repl_user'@'localhost' (using password: YES)
2018-12-31  1:33:47 140385711261440 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dbjpanda** [comment]
Okay I figured out that `--binlog-do-db=drupal` doesn't replicate the user tables from master to slave. SO when I pass another command like `--binlog-do-db=user` it solves the issue. 

But it seems even if I define below variables it doesn't create the tables on slave. It is confusing.  Is it a desired workflow ?
      ```
- MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_USER=test
      - MARIADB_PASSWORD=pass
      - MARIADB_DATABASE=drupal
```

**Comment by juan131** [comment]
Hi @dbjpanda 

As you mentioned when you use that flag it exclusively replicate the databases you list. Therefore, you need to pass the flat multiple times to replicate multiple databases. In the link below you can find more information:

https://mariadb.com/kb/en/library/using-and-maintaining-the-binary-log/#selectively-logging-to-the-binary-log

Regarding the second error, can you try with the docker-compose.yaml below?

```
version: '2'

services:
  mariadb-master:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=master_root_password
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=my_database
  mariadb-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=master_root_password
```
