### ISSUE TITLE
New slaves can't be created after purging master binlogs

### ISSUE THREAD

**Issue by danclough** [bitnami/bitnami-docker-mariadb#177]
**Description**
New slaves cannot be created if binary logs have been purged on the master.

From reading closed issues, it appears that previous versions of this container (1+ year ago) would run a mysqldump on new slaves to populate the local databases and users, but that process was deprecated due to out-of-memory situations caused by large databases.  Reviewing the libmysql.sh file confirms that there are no processes during startup that initialize a new slave with data from the master, instead relying on the existence of the full set of master binary logs to "catch up" a slave from its initial state.

So long as the master binary logs have _not_ been purged, new slaves can read all of the binary logs from `mysql-bin.000001` onward and will initialize as expected.  However, once any logs are purged from the master, no new slaves can be created.

**Steps to reproduce the issue:**
1. Create new cluster using docker-compose.
```yaml
version: '2'

services:
  mariadb-master:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    volumes:
      - './data:/bitnami'
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_pass
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_pass
      - MARIADB_ROOT_PASSWORD=root_pass
  mariadb-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_pass
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_pass
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=root_pass
      - BITNAMI_DEBUG=true
```
2. Create new table on the database.
```
CREATE TABLE `my_database`.`my_table` ( `id` INT NOT NULL AUTO_INCREMENT , `value` VARCHAR(32) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
```
3. Flush logs on master to force creation of new binary log `mysql-bin.000003`.
`mysql> FLUSH LOGS;`
4. Run an insert of some kind to populate a transaction in the new binary log.
```INSERT INTO `my_database`.`my_table` (id, value) VALUES (1, 'testing'),(2, 'replication');```
5. Purge previous logs.
`mysql> PURGE BINARY LOGS to 'mysql-bin.000003';`
6. Scale mariadb-slave to 0 instances.
`# docker-compose up -d --scale mariadb-slave=0`
7. Scale mariadb-slave back up to 1 instance.
`# docker-compose up -d --scale mariadb-slave=1`

**Describe the results you received:**
Slave SQL thread fails to start because the local slave state is out of sync with the beginning of the first available master log.
```
mariadb-slave_1   | 2019-01-14  0:13:32 140715081734912 [Note] Slave SQL thread initialized, starting replication in log 'FIRST' at position 0, relay log './mysql-relay-bin.000001' position: 4
mariadb-slave_1   | 2019-01-14  0:13:32 140715082038016 [Note] Slave I/O thread: connected to master 'repl_user@mariadb-master:3306',replication started in log 'FIRST' at position 4
mariadb-slave_1   | 2019-01-14  0:13:32 140715081734912 [ERROR] Slave SQL: Error 'Unknown database 'my_database'' on query. Default database: 'my_database'. Query: 'CREATE TABLE `my_database`.`my_table` ( `id` INT NOT NULL ,  `value` VARCHAR(32) NOT NULL ) ENGINE = InnoDB', Gtid 0-356-11, Internal MariaDB error code: 1049
mariadb-slave_1   | 2019-01-14  0:13:32 140715081734912 [Warning] Slave: Unknown database 'my_database' Error_code: 1049
mariadb-slave_1   | 2019-01-14  0:13:32 140715081734912 [ERROR] Error running query, slave SQL thread aborted. Fix the problem, and restart the slave SQL thread with "SLAVE START". We stopped at log 'mysql-bin.000002' position 327
mariadb-slave_1   | 2019-01-14  0:13:32 140715081734912 [Note] Slave SQL thread exiting, replication stopped in log 'mysql-bin.000002' at position 327
```
Starting the slave in this state would require the operator to perform a mysqldump to catch up to the start of the master logs.

However, root login is not available on the slave instance because all users other than `mysql.sys` are deleted during `mysql_initialize()` in `libmysql.sh`.

**Describe the results you expected:**
Slave performs a mysqldump process from the master during initialization to bring itself up to date before starting replication.

**Additional information you deem important (e.g. issue happens only occasionally):**
This primarily occurs when starting a new slave with a fresh persistent volume, or a slave with no persistence at all.  It may also occur when starting up a slave that has been stopped for some time.

**Version**

- Output of `docker version`:

```
Docker version 18.09.0, build 4d60db4
```

- Output of `docker info`:

```
Containers: 28
 Running: 25
 Paused: 0
 Stopped: 3
Images: 63
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 31.21GiB
Name: titan.lan
ID: V7HB:R4IH:UZPM:KKWR:5C4K:QMJA:ME35:WDP6:AAF4:45RY:NYYJ:N4JP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
