### ISSUE TITLE
Connect to database bitnami_testlink on Host mariadb:3306 fails

### ISSUE THREAD

**Issue by seasoncool** [bitnami/bitnami-docker-mariadb#188]
**Description**

The mariadb unable to start after the container started with data persistence;

**Here we docker-compose file:**

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Shanghai
    ports:
      - '3306:3306'
    volumes:
      - './mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:1'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Shanghai
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './testlink_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local

```

**Steps to reproduce the issue:**

We want to testlink data migration into another ubuntu server;

However after we started with docker-compose file, the container can started with UP status, but 

the DB looks hang on at Running mysql_urgrade.... for few hours,like below image;

![image](https://user-images.githubusercontent.com/6467295/62336850-d0daaf00-b504-11e9-824b-2e9495697960.png)

**Describe the results you received:**

open my testlink address and got error as below:

![image](https://user-images.githubusercontent.com/6467295/62336644-d388d480-b503-11e9-9cff-c1730ce2c69e.png)

**Describe the results you expected:**

testlink opened successfully with my data persistence

**Version**

Docker version 19.03.1, build 74b1e89e8a

Client:
 Debug Mode: false

Server:
```
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-45-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.55GiB
 Name: james-HP-ProDesk-600-G3-MT
 ID: NH4V:M6L6:WA5H:KWPS:4QPZ:73EJ:CJ4T:C62I:6T3Y:XZ6K:DREE:PX6X
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://172.17.202.233:8080/
 HTTPS Proxy: http://172.17.202.233:8080/
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

docker-compose version 1.24.1, build 4667896b

Linux version 4.15.0-45-generic (buildd@lcy01-amd64-027) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019
