### ISSUE TITLE
Stuck running mysql_upgrade on Azure Container Instance

### ISSUE THREAD

**Issue by davidcv5** [bitnami/bitnami-docker-mariadb#189]
**Description**

Running mysql_ugprade on Azure Container Instance gets stuck sometimes if the container restarts even though my configuration is very simple.

**Steps to reproduce the issue:**

1. Create an Azure File Share (ghost-share, mariadb-share)
2. Deploy container group with the configuration below

```yaml
apiVersion: '2018-10-01'
location: eastus
name: ghost-instance
properties:
  containers:
  - name: mariadb
    properties:
      environmentVariables:
      - name: ALLOW_EMPTY_PASSWORD
        value: 'no'
      - name: MARIADB_ROOT_PASSWORD
        value: my-root-password
      image: bitnami/mariadb:10.3
      ports:
      - port: 3306
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 2.0
      volumeMounts:
      - mountPath: /bitnami
        name: mariadb-data
  - name: ghost
    properties:
      environmentVariables:
      ... ghost environment
      image: bitnami/ghost:2
      ports:
      - port: 2368
      resources:
        requests:
          cpu: 1
          memoryInGB: 1
      volumeMounts:
      - mountPath: /bitnami2
        name: ghost-data
  ipAddress:
    ports:
    - port: 2368
      protocol: TCP
    type: Public
  osType: Linux
  volumes:
  - azureFile:
      shareName: ghost-share
      storageAccountName: my-account
      storageAccountKey: my-account-key
    name: ghost-data
  - azureFile:
      shareName: mariadb-share
      storageAccountName: my-account
      storageAccountKey: my-account-key
    name: mariadb-data
tags: null
type: Microsoft.ContainerInstance/containerGroups


```

**Describe the results you received:**

When starting from scratch, everything works as expected, and even after some container restarts, but at some point, after a restart it just gets stuck and doesn't even restart the container again.

Here are the logs,

```
[0m
[0m[1mWelcome to the Bitnami mariadb container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-mariadb[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-mariadb/issues[0m
[0mSend us your feedback at [1mcontainers@bitnami.com[0m
[0m
[0m[38;5;2mINFO [0m ==> ** Starting MariaDB setup **
[0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_*/MARIADB_* env vars..
[0m[38;5;2mINFO [0m ==> Initializing mariadb database...
[0m[38;5;2mINFO [0m ==> Persisted data detected. Restoring...
[0m[38;5;2mINFO [0m ==> Running mysql_upgrade...
```

**Describe the results you expected:**

Expect mariadb container to always work even after many restarts with the corresponding persisted data.

**Additional information you deem important (e.g. issue happens only occasionally):**

I haven't found a common case when this when happens, it works fine after some restarts, but then just gets stuck.

**Version**

```
bitnami/mariadb:10.3
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using Azure Container Instances, deploying MariaDB with Ghost as a Container Group.
