### ISSUE TITLE
getting "mkdir: cannot create directory '/bitnami/mariadb': Permission denied"

### ISSUE THREAD

**Issue by richb201** [bitnami/bitnami-docker-mariadb#193]
I am trying to install a bitnami LAMP image and am following their instructs. They say to run in a compose-docker.yml. 
```yaml
Version: '2'

services:
  apache:
    image: bitnami/apache:latest
    ports:
      - 80:8080
    volumes:
      - ./apache-vhost/myapp.conf:/vhosts/myapp.conf:ro
      - .:/app

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=cb37trwso*
    volumes:
      - ./mariadb-data:/bitnami

  php-fpm:
    image: bitnami/php-fpm:latest
    volumes:
      - .:/app
```
I have also added a codeigniter  image. 
```yaml
codeigniter:
    image: 'bitnami/codeigniter:3'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
```
The load of mariaDB is failing with the following error in the log:
```
NFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
mkdir: cannot create directory '/bitnami/mariadb': Permission denied
INFO  ==> Stopping mariadb...
```
I am not sure, but I wonder if the directory `/bitnami/mariadb` has permissions that I can change? I tried changing permissions on `/myapp/` to 777 but that didn't seem to work. What am I doing wrong?

**Comment by carrodher** [comment]
Is there any reason to persist the whole `/bitnami` directory instead of `/bitnami/mariadb`?
```yaml
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
```
In your case, you should configure the proper permissions to your local directory `mariadb_data`.
I am not sure if you are using a full `docker-compose.yml` or there are some missing sections, like the volumes one at the end of the file:
```
volumes:
  mariadb_data:
    driver: local
```
Check https://github.com/bitnami/bitnami-docker-mariadb/blob/master/docker-compose.yml

**Comment by richb201** [comment]
Thanks. I am using the bitnami document build a AMP container (https://docs.bitnami.com/containers/how-to/create-amp-environment-containers/). I modified it slightly to add CI and also the password. I am just trying to get my FIRST container up and going. I have copied the actual yml below. I have no idea of why the "WHOLE" directory. I just want to try out getting a container up. 

version: '2'

services:

  apache:
    image: bitnami/apache:latest
    ports:
      - 80:8080
    volumes:
      - ./apache-vhost/myapp.conf:/vhosts/myapp.conf:ro
      - .:/app

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=abcdefg
    volumes:
      - ./mariadb-data:/bitnami

  php-fpm:
    image: bitnami/php-fpm:latest
    volumes:
      - .:/app

  codeigniter:
    image: 'bitnami/codeigniter:3'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mariadb

**Comment by carrodher** [comment]
I see, there is a typo in the guide you are following, thanks for reporting it. I just created an internal task to fix it.

There are several ways to declare volumes on the fly as part of the service declaration, in this case, it seems we are mixing two concepts:
- On one hand, you can use a local directory (if it doesn't exist, it is created by the Docker Engine)
- On the other hand, you can use named volumes

Using the first approach (the one documented in the guide), you need to ensure that the local folder (`mariadb-data`) has the correct permissions, you can do it just assigning write permissions to `others`:
```bash
sudo chmod o+w mariadb-data
```
After that, you should be able to run
```bash
docker-compose up -d
```
without any problem.
If the `mariadb-data` doesn't exist because is the first `docker-compose up` execution, you can create it and assign the proper permissions:
```bash
mkdir mariadb-data && sudo chmod o+w mariadb-data
```

Using the second approach, you don't need to create the folder or set the proper permissions because the volume is created using the Docker Engine driver as an object instead of a real directory in your filesystem (I think this is the best approach for databases), you only need to edit the  _docker-compose.yml_, adding the following lines to the end
```yaml
 volumes:
   mariadb-data:
     driver: local
```
and changing the local path in the mariadb service
```diff
   mariadb:
     image: bitnami/mariadb:latest
     environment:
       - MARIADB_ROOT_PASSWORD=cb37trwso*
     volumes:
-      - ./mariadb-data:/bitnami
+      - mariadb-data:/bitnami
```

**TL;DR**
There are 2 options to solve the issue:
**Option 1:**
- `mkdir mariadb-data && sudo chmod o+w mariadb-data`
- `docker-compose up`

**Option 2:**
- Replace `./mariadb-data:/bitnami` by `mariadb-data:/bitnami` (removing `./`) in the _docker-compose.yml_ and add the following lines at the end of the file
```yaml
 volumes:
   mariadb-data:
     driver: local
```
- `docker-compose up`
