### ISSUE TITLE
The pod won't restart

### ISSUE THREAD

**Issue by farcaller** [bitnami/bitnami-docker-mariadb#201]
**Description**

Tried to enable the monitoring sidecar via the helm install upgrade metrics.enabled=true

**Steps to reproduce the issue:**

Install the stable/mariadb chart with the following overrides:

```
db:
  user: user
  name: db

replication:
  enabled: false

master:
  persistence:
    existingClaim: mysql

slave:
  replicas: 0
  persistence:
    enabled: false
```

Later upgrade the chart with `helm upgrade` with the following overrides:

```
db:
  user: user
  name: db

replication:
  enabled: false

master:
  persistence:
    existingClaim: mysql

slave:
  replicas: 0
  persistence:
    enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

**Describe the results you received:**

Mysql crashloops:

```
mysql-mariadb-0 mariadb  10:06:37.11
mysql-mariadb-0 mariadb  10:06:37.11 Welcome to the Bitnami mariadb container
mysql-mariadb-0 mariadb  10:06:37.11 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mysql-mariadb-0 mariadb  10:06:37.11 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mysql-mariadb-0 mariadb  10:06:37.12 Send us your feedback at containers@bitnami.com
mysql-mariadb-0 mariadb  10:06:37.12
mysql-mariadb-0 mariadb  10:06:37.14 INFO  ==> ** Starting MariaDB setup **
mysql-mariadb-0 mariadb  10:06:37.23 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql-mariadb-0 mariadb  10:06:37.24 INFO  ==> Initializing mariadb database
mysql-mariadb-0 mariadb  10:06:37.26 INFO  ==> Using persisted data
mysql-mariadb-0 mariadb  10:06:37.28 INFO  ==> Running mysql_upgrade
mysql-mariadb-0 mariadb  10:06:37.28 INFO  ==> Starting mariadb in background
mysql-mariadb-0 mariadb  10:06:38.32 INFO  ==> Stopping mariadb
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg="Starting mysqld_exporter (version=0.12.1, branch=HEAD, revision=48667bf7c3b438b5e93b259f3d17b70a7c9aff96)" source="mysqld_exporter.go:257"
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg="Build context (go=go1.12.7, user=root@0b3e56a7bc0a, date=20190729-12:35:58)" source="mysqld_exporter.go:258"
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg="Enabled scrapers:" source="mysqld_exporter.go:269"
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg=" --collect.global_variables" source="mysqld_exporter.go:273"
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg=" --collect.slave_status" source="mysqld_exporter.go:273"
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg=" --collect.global_status" source="mysqld_exporter.go:273"
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg=" --collect.info_schema.query_response_time" source="mysqld_exporter.go:273"
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg=" --collect.info_schema.innodb_cmp" source="mysqld_exporter.go:273"
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg=" --collect.info_schema.innodb_cmpmem" source="mysqld_exporter.go:273"
mysql-mariadb-0 metrics time="2019-10-28T10:06:37Z" level=info msg="Listening on :9104" source="mysqld_exporter.go:283"
mysql-mariadb-0 metrics time="2019-10-28T10:06:47Z" level=error msg="Error pinging mysqld: dial tcp [::1]:3306: connect: connection refused" source="exporter.go:146"
```

**Describe the results you expected:**

Mysql keeps working

**Version**

This is docker.io/bitnami/mariadb:10.3.18-debian-9-r36
