### ISSUE TITLE
init script.sql not working with injectSecretsAsVolume: true helm value

### ISSUE THREAD

**Issue by summed** [bitnami/bitnami-docker-mariadb#213]
**Description**

This might belong in the bitnami/charts issues, but I suspect the issue is located in this repo, so therefor I'm posting it here.

If using the injectSecretsAsVolume: true option, then the passwords are mounted as files into /opt/bitnami/mysql/secrets/ ...

When the mariadb container starts it fails when trying to load the init *.sql files from the /docker-entrypoint-initdb.d, when using the injectSecretsAsVolume option.

https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.4/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L456 (function mysql_custom_init_scripts())

if I manually load the script via `mysql -u root -p < init.sql` on the container then I have no problem.

Also if I set the injectSecretsAsVolume: false and set the passwords for root, db and the replication objects, then the /docker-entrypoint-initdb.d/* execute without issues.

I suspect its a password issue in the script.

**Steps to reproduce the issue:**

Installing via helm with these values:
```
---
  metrics: 
    enabled: true
  rootUser:
    #password: "arootpassword"
    injectSecretsAsVolume: true
  db: 
    user: "ocs"
    name: "ocs"
    #password: "adbpassword"
    injectSecretsAsVolume: true
  replication:
    #password: "areppassword"
    enabled: true
    injectSecretsAsVolume: true
  master: 
    extraFlags: "--innodb_autoinc_lock_mode=0"
    persistence: 
      enabled: true
      size: "10Gi"
      storageClass: ""
  slave: 
    extraFlags: "--innodb_autoinc_lock_mode=0"
    replicas: "1"
    persistence: 
      enabled: true
      size: "10Gi"
      storageClass: ""
  service: 
    type: "ClusterIP"
    nodePort: 
      master: ""
      slave: ""
  initdbScriptsConfigMap: "init-scripts"
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
lient:
 Debug Mode: false

Server:
 Containers: 167
  Running: 107
  Paused: 0
  Stopped: 60
 Images: 130
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-91-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 216.5GiB
 Name: k8s-node-dev-03
 ID: 6VUV:YHCX:GIVK:D3YC:YYZQ:RGJ4:3OGM:AB62:NWFH:CV27:2QVH:2E5R
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Helm chart version 7.3.16 (using docker.io/bitnami/mariadb:10.3.22-debian-10-r60 image)

**Comment by juan131** [comment]
Hi @summed 

When you enable `injectSecretsAsVolume`, the unique difference is that MariaDB is configured taken credentials from files mounted in the system, instead of taking them from environment variables. However, there are no difference regarding how MariaDB is configured.

In the values you shared, you both set this property to `true` and commented the "password" fields. When this happens, these values are **randomly generated**, see https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/templates/secrets.yaml#L9

This means that you don't know the passwords that will be set for "root" nor "ocs" users. Therefore, whatever script you're using is failing due to wrong credentials.

My recommendation: set the "passwords" fields so you avoid them to be randomly generated:

```yaml
  rootUser:
    password: XXXXXX
    injectSecretsAsVolume: true
  db: 
    user: ocs
    name: ocs
    password: YYYYYY
    injectSecretsAsVolume: true
  replication:
    password: ZZZZZZ
    enabled: true
    injectSecretsAsVolume: true
```
