### ISSUE TITLE
Data doesn't persist between image rebuilds

### ISSUE THREAD

**Issue by andfinally** [bitnami/bitnami-docker-mariadb#220]
**Description**

I've recently started using this image with a small replication setup in a dev environment. I'm finding that with this setup, data is not persisted between container rebuilds. 

**Steps to reproduce the issue:**

1. Create docker file with two database containers:

```yml
version: '3.5'

services:
  db:
    container_name: "primary_db"
    image: docker.io/bitnami/mariadb:10.2-debian-10
    restart: always
    ports:
      - "5881:3306"
    environment:
      MARIADB_DATABASE: test
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      MARIADB_ROOT_PASSWORD: 'test'
      # Replication
      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: 'repl_user'
      MARIADB_REPLICATION_PASSWORD: 'testsecretpassword'
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - "./docker/data/mysql:/var/lib/mysql:delegated"
      - "./docker/data/dumps/:/docker-entrypoint-initdb.d/"

  db-replica:
    container_name: "secondary_db"
    image: docker.io/bitnami/mariadb:10.2-debian-10
    restart: always
    ports:
      - "5884:3306"
    depends_on:
      - db
    environment:
      MARIADB_DATABASE: test
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      # Replication
      MARIADB_REPLICATION_MODE: slave
      MARIADB_REPLICATION_USER: 'repl_user'
      MARIADB_REPLICATION_PASSWORD: 'testsecretpassword'
      MARIADB_MASTER_HOST: db
      MARIADB_MASTER_PORT_NUMBER: 3306
      MARIADB_MASTER_ROOT_PASSWORD: 'test'
      ALLOW_EMPTY_PASSWORD: 'yes'

networks:
  default:
    name: "test"
```
2. Add a record to the database in the primary DB, and see it replicated in the secondary DB.
3. Stop and remove the containers:

```
docker-compose down
docker container prune
```

4. Rebuild and restart the containers:

```
docker-compose up --build --force-recreate
```

5. Confirm the added record isn't in the database.

**Describe the results you received:**

After I rebuild my containers, data I added to the database has vanished.

**Describe the results you expected:**

I expect data to persist in the shared volume.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time. When I use the Docker `mariadb` image and remove the replication config, data persists between container rebuilds.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 295
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: Y4TQ:VQYS:2GFG:HE5Q:7Z3K:GPOC:DHXH:M2XH:GIYR:EQH5:GNVF:TVQS
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 114
  Goroutines: 143
  System Time: 2020-07-11T13:44:21.8122676Z
  EventsListeners: 7
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Containers are run on a Catalina Mac using Docker Desktop 2.3.0.3
