### ISSUE TITLE
timezone issue

### ISSUE THREAD

**Issue by haarchri** [bitnami/bitnami-docker-mariadb#222]
hello we have issues with the timezone in bitnami mariadb docker container 

` [Failed SQL: (1064) SET time_zone = 'Europe/Berlin';`

Did you have any idea to set the timezones ? looks like the needed tables are empty ... 
so we checked something like: https://gist.github.com/brianburridge/11298396 but it doesn't help because of the mysqld restart is needed ...

**Comment by andresbono** [comment]
Hi @haarchri, thanks for opening this issue. How are you running the container? Where are you finding that error message?

**Comment by haarchri** [comment]
hello, we using bitnami mariadb as docker container  

if you have a stored procedure and you want to set a time_zone only in stored procedure  `SET time_zone = 'Europe/Berlin'; ` you get the 1064 issue because of no timezone data loaded

**Comment by andresbono** [comment]
Hi @haarchri, I'm not really sure how you got into that error...

What we tried:

In the host machine:

```
docker run --rm -d --name mariadb -e ALLOW_EMPTY_PASSWORD=yes bitnami/mariadb
docker exec -it mariadb bash
```

In the container:

```
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
mysql -u root
```

In the MySQL shell:
```
> SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
+--------------------+---------------------+
| @@GLOBAL.time_zone | @@SESSION.time_zone |
+--------------------+---------------------+
| SYSTEM             | SYSTEM              |
+--------------------+---------------------+
1 row in set (0.000 sec)

> SET GLOBAL time_zone = 'Europe/Berlin';
Query OK, 0 rows affected (0.000 sec)

> SET time_zone = 'Europe/Berlin';
Query OK, 0 rows affected (0.000 sec)

> SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
+--------------------+---------------------+
| @@GLOBAL.time_zone | @@SESSION.time_zone |
+--------------------+---------------------+
| Europe/Berlin      | Europe/Berlin       |
+--------------------+---------------------+
1 row in set (0.000 sec)
```


Docs:

- https://dev.mysql.com/doc/refman/8.0/en/mysql-tzinfo-to-sql.html
- https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html


Please note that we highly recommend you to do a backup of your data in case some of the actions goes wrong.

**Comment by haarchri** [comment]
we starting the docker container in gitlab-ci pipeline step as service container - and it looks like that we are unable to execute the tz information - is it possible to ship the tz via bitnami base image ?

```yaml
"Liquibase validation empty database":
  stage: "Test Liquibase"
  extends: .liquibase_validate_empty_database_template
  services:
    - name: bitnami/mariadb:10.3.22-ol-7-r13
  variables:
    MYSQL_ROOT_PASSWORD: "****"
    MARIADB_ROOT_PASSWORD: "****"
````

first step is:

`$ mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u $USER -p$PASSWORD -h 127.0.0.1 -D mysql
liquibase update`

after that we got a syntax error: 
`Unexpected error running Liquibase: (conn=33) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INSERT INTO `test` [Failed SQL: (1064) SET time_zone = 'Europe/Berlin';`

if we execute our liquibase update in a AWS RDS Database for example it is working - here are all tzinfo inserted by default

**Comment by andresbono** [comment]
And @haarchri, would it make sense to just change the time zone of the container? `-e TZ='Europe/Berlin'`. Taking advantage of the default value `SYSTEM` of MariaDB `@@GLOBAL.time_zone`:

```
docker run --rm -d --name mariadb -e TZ='Europe/Berlin' -e ALLOW_EMPTY_PASSWORD=yes bitnami/mariadb
docker exec -it mariadb mysql -u root -e 'SELECT CURRENT_TIME();'
+----------------+
| CURRENT_TIME() |
+----------------+
| 13:32:16       |
+----------------+

```

**Comment by mephinet** [comment]
@haarchri: My understanding is this:
The timezones are available on the OS level (in /usr/share/zoneinfo/) - but they are _not_ imported into MariaDB by the entrypoint scripts. To get this done, try adding the following to your values.yaml:

```yaml
initdbScripts:
  import_timezones.sh: |
    #! /bin/sh
    mariadb-tzinfo-to-sql /usr/share/zoneinfo/ | mysql_execute mysql "$DB_ROOT_USER" "$DB_ROOT_PASSWORD"

```
