### ISSUE TITLE
After restart The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable.

### ISSUE THREAD

**Issue by maggie-drupal** [bitnami/bitnami-docker-mariadb#225]
We have a Drupal installation using the bitnami drupal helm chart.
We had to restart our mariadb and after this it doesn't restart.
We get the following:
```
mariadb 12:27:46.16 INFO  ==> ** Starting MariaDB setup **
mariadb 12:27:46.19 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 12:27:46.21 INFO  ==> Initializing mariadb database
mariadb 12:27:46.25 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable.
 Configurations based on environment variables will not be applied for this file.
mariadb 12:27:46.26 INFO  ==> Using persisted data
mariadb 12:27:46.32 INFO  ==> Running mysql_upgrade
mariadb 12:27:46.36 INFO  ==> Starting mariadb in background
mariadb 12:27:48.44 INFO  ==> Stopping mariadb
```
How to address this issue?

**Comment by virgil9306** [comment]
I got this too.

Previously I was loading values from a YAML as

```
master:
  persistence:
    size: 5Gi
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
slave:
  persistence:
    size: 5Gi
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
db:
  name: strapi
```

and it was working

but since the terminology was changed I updated the file as follows:

```
primary: # master
  persistence:
    size: 5Gi
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
secondary: # slave
  replicaCount: 1
  persistence:
    size: 5Gi
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
db:
  name: strapi
```

and it no longer creates the correct resources.

Command used:

```
helm upgrade --install helios-cms-db-mariadb \
    --values overrides.yaml \
    --namespace $1 \
    --set db.user=$2 \
    --set db.password=$3 \
    --set db.forcePassword='true' \
    --set rootUser.password=$4 \
    --set rootUser.forcePassword='true' \
    --set replication.password=$5 \
    --set replication.forcePassword='true' \
    bitnami/mariadb
```
