### ISSUE TITLE
When the power is restarted, the database starts abnormally

### ISSUE THREAD

**Issue by diwenzheng** [bitnami/bitnami-docker-mariadb#235]

**Comment by diwenzheng** [comment]
目前mariadb 主从模式下 没有高可用啊,当主挂了,从节点并不能去工作啊,如何通过docker-compose 设置 互为主从关系？

**Comment by migruiz4** [comment]
Hi @diwenzheng,

I'm sorry but in order to give you better assistance and for our answers to be accessible to most of our users, I can only reply to issues in English.

Could you please reopen this issue using English?

**Comment by diwenzheng** [comment]
thanks @migruiz4  I currently have no high availability in MariaDB master-slave mode. When the master is hung, the slave node is not able to work. How do you create a master-slave relationship with each other through docker-compose?

**Comment by diwenzheng** [comment]
I looked at how to do that .then i make a database middleware
 (mycat) to change master or slave .  but i find mush questions and feel this component is heavy . please help me .thanks

**Comment by migruiz4** [comment]
Hi @diwenzheng ,

If you are looking how to configure MariaDB with High Availability, I'd recommend having a look at this document from MariaDB official website: https://mariadb.com/wp-content/uploads/2019/04/mariadb-platform-high-availability-guide_whitepaper_1001.pdf

As you can see in the document, there are two methods to configure your MariaDB with HA:
- The first solution would be setting up MariaDB master/slave architecture with automatic failover using MariaDB MaxScale (v2.2+) (https://github.com/mariadb-corporation/MaxScale) which is currently not supported officially. Meaning you could try it out but we don't have a Bitnami docker image for MaxScale and we haven't tested it so you could find issues in the process. 
- The second solution would be using MariaDB Galera cluster for multi-master clustering, for which I'd recommend having a look at this other repository: https://github.com/bitnami/bitnami-docker-mariadb-galera

In case you are interested in deploying using Kubernetes we also provide a Helm chart for MariaDB Galera cluster https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera

Regarding `mycat` I'm sorry I won't be able to help you as it would be out of my knowledge.

**Comment by diwenzheng** [comment]
@migruiz4 thanks,I find a document. can you help me to Settings are master and slave. it means matster is slave or master,and  slave is master or slave . In this way, we can achieve high reliability between main and standby.

**Comment by diwenzheng** [comment]
i use docker-compose deploy master-slave, and Manual Settings are master and slave to each other . but when the The container is restart .The relationship that I set manually will break. I found that mysql.log or pos change. i think author can do master-slave,please help me to do master is slave or master is master relationship.you can use MARIADB_REPLICATION_MODE is master or slave.Do you think my idea is OK.

**Comment by diwenzheng** [comment]
i find a question. when the db is manual restart. i find the space is not release . 
![image](https://user-images.githubusercontent.com/60613511/111935887-6de5c380-8aff-11eb-98b6-268c15ff34a7.png)

**Comment by migruiz4** [comment]
Changing the containers manually to change roles won't persist a container restart because their roles are set in the Docker-file:
https://github.com/bitnami/bitnami-docker-mariadb/blob/master/docker-compose-replication.yml

For HA I'd recommend using instead a MariaDB Galera cluster:  https://github.com/bitnami/bitnami-docker-mariadb-galera

For example, using a docker-compose like this:
```
version: '2.1'

services:
  mariadb-galera-0:
    image: 'docker.io/bitnami/mariadb-galera:10.5-debian-10'
    volumes:
      - 'mariadb_galera_0_data:/bitnami/mariadb'
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=my_root_password
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=my_database
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  mariadb-galera-1:
    image: 'docker.io/bitnami/mariadb-galera:10.5-debian-10'
    links:
      - "mariadb-galera-0:mariadb-galera"
    volumes:
      - 'mariadb_galera_1_data:/bitnami/mariadb'
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=my_root_password
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      mariadb-galera-0:
        condition: service_healthy
volumes:
  mariadb_galera_0_data:
    driver: local
  mariadb_galera_1_data:
    driver: local
```

Regarding your question: 
>  i find the space is not release .

This is because volumes will persist after the container has been removed. You can manage volumes using `docker` command.

For example:
```bash
#List all volumes
$ docker volume list
#Remove one or more volumes
$ docker volume rm my_volume_1 my_volume_2
```
