### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES) on slave container

### ISSUE THREAD

**Issue by ansidev** [bitnami/bitnami-docker-mariadb#247]
**Description**

`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

**Steps to reproduce the issue:**

1. Run `docker exec -it {slave_container_name} bash`.
2. Run `mariadb -uroot -p`, then press Enter and paste copied password.
3. Press Enter.

**Describe the results you received:**

`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

**Describe the results you expected:**

Connect successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**docker-compose.yaml**

```
version: '3.8'

services:
  mariadb-master:
    image: docker.io/bitnami/mariadb:10.5
    container_name: ${MASTER_DB_HOST}
    restart: always
    expose:
      - ${MASTER_DB_PORT}
    volumes:
      - 'mariadb_master_data:/bitnami/mariadb'
    environment:
      - MARIADB_CHARACTER_SET=${DB_CHARACTER_SET}
      - MARIADB_COLLATE=${DB_COLLATE}
      - MARIADB_ROOT_PASSWORD=${MASTER_DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${MASTER_DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=${DB_REPLICATION_USER}
      - MARIADB_REPLICATION_PASSWORD=${DB_REPLICATION_PASSWORD}
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mariadb-slave:
    image: docker.io/bitnami/mariadb:10.5
    restart: always
    expose:
      - ${SLAVE_DB_PORT}
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_CHARACTER_SET=${DB_CHARACTER_SET}
      - MARIADB_COLLATE=${DB_COLLATE}
      - MARIADB_ROOT_PASSWORD=${SLAVE_DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${SLAVE_DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=${DB_REPLICATION_USER}
      - MARIADB_REPLICATION_PASSWORD=${DB_REPLICATION_PASSWORD}
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${MASTER_DB_ROOT_PASSWORD}
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mariadb_master_data:
    driver: local
```

**Environment variables**
(Something was not provided, you can use your value to reproduce this issue)

```
DB_CHARACTER_SET=utf8mb4
DB_COLLATE=utf8mb4_unicode_ci
DB_DATABASE=
DB_REPLICATION_PASSWORD=
DB_REPLICATION_USER=repl
DB_USER=db_user
DOCKER_NETWORK=net_001
MASTER_DB_HOST=mariadb_master
MASTER_DB_PASSWORD=master_password
MASTER_DB_PORT=3306
MASTER_DB_ROOT_PASSWORD=master_root_password
SLAVE_DB_PASSWORD=slave_password
SLAVE_DB_PORT=3306
SLAVE_DB_ROOT_PASSWORD=slave_root_password
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:59 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:40 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 153
  Running: 21
  Paused: 0
  Stopped: 132
 Images: 691
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: bzs8hptt4pb1gpy5f2mawnxhe
  Is Manager: false
  Node Address: 10.0.158.204
  Manager Addresses:
   10.0.158.104:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-81-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 8GiB
 Name: ubuntu
 ID: GSA3:3XBB:M7SA:XT7W:X5XV:QGIG:675D:7H3Q:LP5S:NUVG:ISWL:K3QC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
