### ISSUE TITLE
ERROR 1449 (HY000) at line 820: The user specified as a definer ('root'@'localhost') does not exist

### ISSUE THREAD

**Issue by antonio24073** [bitnami/bitnami-docker-mariadb#249]
Hi,
With BITNAMI_DEBUG=true, I got:
```
Phase 4/7: Running 'mysql_fix_privilege_tables'
ERROR 1449 (HY000) at line 820: The user specified as a definer ('root'@'localhost') does not exist
FATAL ERROR: Upgrade failed
```
this is my Dockerfile:
```
FROM bitnami/mariadb
ENV MARIADB_PORT_NUMBER=3306
EXPOSE 3306
```
this is my docker-compose.yml
```
version: '3.8'
services:
    mariadb:
        container_name: mariadb
        build: ./docker/docker-files/mariadb
        restart: always
        ports:
           - 127.0.0.26:3306:3306
        environment:
            - MARIADB_ROOT_USER=dsdsfsdfdfssdfsd
            - MARIADB_ROOT_PASSWORD=gdgdfgdgdgdd
            - MARIADB_DATABASE=fhghfghhgh
            - MARIADB_USER=hjghhghjgjhgj
            - MARIADB_PASSWORD=hjjkjkkjkhjkjhk
            - MARIADB_SKIP_TEST_DB=yes
            - WORDPRESS_DATABASE_PORT_NUMBER=3306
            - BITNAMI_DEBUG=true
        volumes:
            - ./docker/volumes/mariadb/mariadb:/bitnami/mariadb
        networks:
            my_network:
                ipv4_address: 172.16.238.16
                ipv6_address: 2001:3984:3989::16
        # secrets: 
        #     - db_root_user
        #     - db_root_password
        #     - db_database
        #     - db_password
        #     - db_user
networks:
    my_network:
        name: plit_network
        driver: bridge
        ipam:
            config:
                - subnet: "172.16.238.0/24"
                - subnet: "2001:3984:3989::/64"
# secrets:
#     db_password:
#         file: ./pass.txt
#     db_database:
#         file: ./pass.txt
#     db_user:
#         file: ./pass.txt
#     db_root_user:
#         file: ./pass.txt
#     db_root_password:
#         file: ./pass.txt
# secrets:
#     db_password:
#         external: true
#     db_database:
#         external: true
#     db_user:
#         external: true
#     db_root_user:
#         external: true
#     db_root_password:
#         external: true
```
My first try is with external password. My second try is with secret file. After I tried writing the passwords.
In each try, I do:
```
sudo rm -Rf docker/volumes/mariadb/mariadb/*
sudo chown -R 1001:1001 ./docker/volumes/mariadb/mariadb
```
this never happened
Does the environment variables change the password on the volume?

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 8
  Running: 6
  Paused: 0
  Stopped: 2
 Images: 100
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: knn3yq31zio8ouwlrbxmzlyfv
  Is Manager: true
  ClusterID: kuf5wbnb83931ynfnb5e3l1hl
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.0.26
  Manager Addresses:
   192.168.0.26:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-17-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.949GiB
 Name: debian-2
 ID: NAKE:FJ3M:R35T:X7MY:KTVX:IE5A:XCTK:UXI3:IM6K:GVVY:T4QG:G54S
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

I'm in a virtualbox with debian 10.
