### ISSUE TITLE
Host 'xxx.xxx.xxx.xxx' is not allowed to connect to this MariaDB server

### ISSUE THREAD

**Issue by andrewmclagan** [bitnami/bitnami-docker-mariadb#34]
When booting through `docker-compose` I get:

`[PDOException]`
`SQLSTATE[HY000] [1130] Host '172.17.0.5' is not allowed to connect to this MariaDB server`

the docker compose snippet looks like this:

```
# ---------------------------    
# Database Service    
# --------------------------- 

database:
    image: bitnami/mariadb
    environment:
        - MARIADB_DATABASE=my_database_name 
        - MARIADB_PASSWORD=myAmazingPassword
        - MARIADB_REPLICATION_MODE=master
        - MARIADB_REPLICATION_USER=db_slave_usr
        - MARIADB_REPLICATION_PASSWORD=ReplicationPassword  
    ports:
        - "3306:3306"  

database_slave:
    image: bitnami/mariadb
    links:
        - database:master     
    environment:
        - MARIADB_REPLICATION_MODE=slave   

# ---------------------------    
# API Service
# --------------------------- 

api:
    build: ./php-src-files
    links:
        - database           
    environment:
        - DB_DATABASE=my_database_name          
        - DB_PASSWORD=myAmazingPassword   
        
```
