### ISSUE TITLE
Slave MariaDB containers fails to connect after stop

### ISSUE THREAD

**Issue by hnq90** [bitnami/bitnami-docker-mariadb#39]
When I'm using Bitnami's Mariadb image, I faced weird issue:

**First time:**
Execute: `docker-compose scale master=1 slave=2`
> Everything is OK.
> I can access to mysql server of both slaves container by go to it: docker exec -it <slave_container_id> mysql -u root -p123456

But after I stop all containers by: `docker stop $(docker ps -a -q)`
And start all containers again: `docker-compose scale master=1 slave=2`
I couldn't access to mysql server on slaves containers: `docker exec -it <slave_container_id> mysql -u root -p123456`
> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

And try to get logs from `docker logs`:
```
160303  6:54:42 [Note] Plugin 'FEEDBACK' is disabled.
160303  6:54:42 [Note] Server socket created on IP: '0.0.0.0'.
160303  6:54:42 [Warning] 'proxies_priv' entry '@ root@e8be7521dce3' ignored in --skip-name-resolve mode.
160303  6:54:42 [Note] Slave SQL thread initialized, starting replication in log 'mysql-bin.000007' at position 1350, relay log './mysql-relay-bin.000014' position: 1634
160303  6:54:42 [Note] Event Scheduler: Loaded 0 events
ERROR: 1396  Operation CREATE USER failed for 'root'@'%'
160303  6:54:42 [Note] mysqld.bin: ready for connections.
Version: '5.5.46-MariaDB-log'  socket: '/opt/bitnami/mysql/tmp/mysql.sock'  port: 3306  MariaDB Server
160303  6:54:42 [Note] Slave I/O thread: connected to master 'repl_user@mariadb_master:3306',replication started in log 'mysql-bin.000007' at position 1350
```

I have to create `root` user to create new databases and users for HAProxy.

This is my docker-compose.yml:
```
version: '2'

services:
  master:
    image: bitnami/mariadb:development
    networks:
      - back
    volumes:
      - /var/mariadb/db/master/data:/bitnami/mariadb/data
      - /var/mariadb/db/master/conf:/bitnami/mariadb/conf
    environment:
      MARIADB_PASSWORD: 123456
      MARIADB_DATABASE: testdb
      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: repl_user
      MARIADB_REPLICATION_PASSWORD: repl_pass
      TERM: xterm
    restart: on-failure:3
  slave:
    image: bitnami/mariadb:development
    networks:
      - back
    environment:
      MARIADB_PASSWORD: 123456789
      MARIADB_DATABASE: testdb
      MARIADB_REPLICATION_MODE: slave
      MARIADB_REPLICATION_USER: repl_user
      MARIADB_REPLICATION_PASSWORD: repl_pass
      MARIADB_MASTER_HOST: master
      MARIADB_MASTER_USER: root
      MARIADB_MASTER_PASSWORD: 123456
      TERM: xterm
    links:
      - master:master
    depends_on:
      - master
    restart: on-failure:3
networks:
  back:
    driver: bridge
```

Did there anyone face the same kind of this problem? :(
