### ISSUE TITLE
Slaves failing to connect to master in Kubernetes after 36 retries.

### ISSUE THREAD

**Issue by ellisio** [bitnami/bitnami-docker-mariadb#51]
Hello,

I have been attempting to deploy a 1+3 setup on Kubernetes in the Google Container Engine. The Master comes up just fine. However, the 3 slaves all fail... I can't seem to figure out what is causing the them to fail as these containers come up fine with Docker Compose locally on OS-X.

The error that is coming up from the slaves is:

```
Error executing 'postInstallation': mysqldump: Got error: 2003: "Can't connect to MySQL server on 'db-master' (111 "Connection refused")" when trying to connect
```

Here are the two Service/Deployment files:

*db-master.yml:*
```yaml
---
  apiVersion: v1
  kind: Service
  metadata:
    name: db-master
    labels:
      app: kickaseminar
      tier: backend
  spec:
    ports:
      - port: 3306
    selector:
      app: kickaseminar
      tier: backend
---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: db-master
    labels:
      app: kickaseminar
      name: db-master
      tier: backend
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: kickaseminar
          name: db-master
          tier: backend
      spec:
        containers:
          - name: db-master
            image: bitnami/mariadb:latest
            ports:
              - containerPort: 3306
            resources:
              limits:
                cpu: 0.5
            env:
              - name: MARIADB_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: kickaseminar
                    key: db-root-password
              - name: MARIADB_REPLICATION_MODE
                value: master
              - name: MARIADB_REPLICATION_USER
                value: replication
              - name: MARIADB_REPLICATION_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: kickaseminar
                    key: db-replication-password
              - name: MARIADB_DATABASE
                value: kickaseminar
              - name: MARIADB_USER
                value: kickaseminar
              - name: MARIADB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: kickaseminar
                    key: db-password
```

*db-slave.yml*
```yaml
---
  apiVersion: v1
  kind: Service
  metadata:
    name: db-slave
    labels:
      app: kickaseminar
      tier: backend
  spec:
    ports:
      - port: 3306
    selector:
      app: kickaseminar
      tier: backend
---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: db-slave
    labels:
      app: kickaseminar
      name: db-slave
      tier: backend
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: kickaseminar
          name: db-slave
          tier: backend
      spec:
        containers:
          - name: db-slave
            image: bitnami/mariadb:latest
            ports:
              - containerPort: 3306
            resources:
              limits:
                cpu: 0.2
            env:
              - name: MARIADB_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: kickaseminar
                    key: db-root-password
              - name: MARIADB_REPLICATION_MODE
                value: slave
              - name: MARIADB_REPLICATION_USER
                value: replication
              - name: MARIADB_REPLICATION_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: kickaseminar
                    key: db-replication-password
              - name: MARIADB_MASTER_HOST
                value: db-master
              - name: MARIADB_MASTER_USER
                value: kickaseminar
              - name: MARIADB_MASTER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: kickaseminar
                    key: db-password
              - name: MARIADB_DATABASE
                value: kickaseminar
              - name: MARIADB_USER
                value: kickaseminar
              - name: MARIADB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: kickaseminar
                    key: db-password
```

Just to be sure I didn't have any configuration issues with the environment variables I ran the following on both master and every slave:

```bash
kubectl exec <container_name> printenv -- | grep MARIADB_
```

All 4 containers had the correct username/passwords set on the environment variables.

The reason I'm confused is because the slaves are failing to connect to `db-master` on their startup. This is odd because your `bitnami/redis:latest` images came up just fine when pointing to `redis-master` as the `REDIS_MASTER_HOST`.

Let me know if there is anything else I can provide to assist with this.

Cheers,
Andrew

**Comment by ellisio** [comment]
I also tried forcing the `MARIADB_MASTER_PORT` in `db-slave.yml` with the following and still no luck.

```yaml
- name: MARIADB_MASTER_PORT
  value: "3306"
```

**Comment by prydonius** [comment]
Hey @ellisio, I'm not sure if this is what's causing you're issue, but I noticed that both the master and slave services have the same selectors which could be causing a conflict.

You should update the db-master service to have:
```
selector:
      app: kickaseminar
      tier: backend
      name: db-master
```

and the db-slave to have
```
selector:
      app: kickaseminar
      tier: backend
      name: db-slave
```

Again, not sure if that's the cause of your particular issue, so let us know if that changes anything. You could also compare your manifests with the [manifests for our mariadb-cluster](https://github.com/bitnami/charts/tree/master/mariadb-cluster/manifests) [Helm](https://github.com/helm/helm-classic) chart.
