### ISSUE TITLE
Error executing 'postInstallation'

### ISSUE THREAD

**Issue by theindra** [bitnami/bitnami-docker-mariadb#79]
I get the following logs in my slave container:

> 2016-10-17T22:20:03.375948892Z mariadb INFO  ==> Creating a data snapshot...
> 2016-10-17T22:20:45.093544554Z Error executing 'postInstallation': "toString()" failed 
> 2016-10-17T22:20:47.543393766Z nami    INFO  Initializing mariadb
> 2016-10-17T22:20:57.142161306Z mariadb INFO  ==> Creating database XXX-prod...
> 2016-10-17T22:20:57.151685217Z Error executing 'postInstallation': ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
> 2016-10-17T22:20:57.151708921Z 

I mapped the volume /bitnami/mariadb to the directory /bikersos/mariadb-prod on the host.
No files are created there!
Any ideas what is wrong here?

**Comment by theindra** [comment]
After restarting docker service and deleting the volumes on the host the error changed. Now i get this message:
2016-10-18T09:35:23.900201317Z 2016-10-18  9:35:22 139714054163200 [Note] Slave SQL thread initialized, starting replication in log 'FIRST' at position 0, relay log './mysql-relay-bin.000001' position: 4 
2016-10-18T09:35:23.900219828Z 2016-10-18  9:35:22 139714054466304 [ERROR] Slave I/O: error connecting to master 'replication_user@master:3306' - retry-time: 60  retries: 86400  message: Access denied for user 'replication_user'@'10.7.0.13' (using password: YES), Internal MariaDB error code: 1045

Stage thing is that this is my production setup and i have the same setup (just with different passwords) for my staging environment. I copied the dockercloud file. So the settings should be the same.

**Comment by sameersbn** [comment]
Hello @theindra, could you please provide more information so as to enable us to better understand/reproduce the issue?  

The following information would be invaluable in helping us track down the issue:

 - Docker host os
 - Are you using docker for mac?
 - Output of `docker info`
 - Sample commands / docker-compose.yml file to reproduce the issue

Also, please try to `docker-compose up` the following `docker-compose.yml` file and let us know the result

```yml
master:
  image: bitnami/mariadb:latest
  environment:
    - MARIADB_ROOT_PASSWORD=root_password
    - MARIADB_REPLICATION_MODE=master
    - MARIADB_REPLICATION_USER=my_repl_user
    - MARIADB_REPLICATION_PASSWORD=my_repl_password
    - MARIADB_USER=my_user
    - MARIADB_PASSWORD=my_password
    - MARIADB_DATABASE=my_database

slave:
  image: bitnami/mariadb:latest
  links:
    - master:master
  environment:
    - MARIADB_ROOT_PASSWORD=root_password
    - MARIADB_REPLICATION_MODE=slave
    - MARIADB_REPLICATION_USER=my_repl_user
    - MARIADB_REPLICATION_PASSWORD=my_repl_password
    - MARIADB_MASTER_HOST=master
    - MARIADB_MASTER_USER=my_user
    - MARIADB_MASTER_PASSWORD=my_password
    - MARIADB_USER=my_user
    - MARIADB_PASSWORD=my_password
    - MARIADB_DATABASE=my_database
```
